// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBdvBK5zasOri0R-r2AFhT89pcDZE7_w',
    appId: '1:648839958281:web:23c80ad1cfaaa986cfcdd8',
    messagingSenderId: '648839958281',
    projectId: 'regmonu',
    authDomain: 'regmonu.firebaseapp.com',
    storageBucket: 'regmonu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGlpmul5RheQjjgd_mT6tMOOUEq4zWzJU',
    appId: '1:648839958281:android:db3de4bba87c9cd5cfcdd8',
    messagingSenderId: '648839958281',
    projectId: 'regmonu',
    storageBucket: 'regmonu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAuLjIQieR57oqx-XZYs4_qTOaLRLaQ8',
    appId: '1:648839958281:ios:f2c4dfa6f7a95708cfcdd8',
    messagingSenderId: '648839958281',
    projectId: 'regmonu',
    storageBucket: 'regmonu.appspot.com',
    iosBundleId: 'com.example.monureg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvAuLjIQieR57oqx-XZYs4_qTOaLRLaQ8',
    appId: '1:648839958281:ios:9cf0624744ff72e5cfcdd8',
    messagingSenderId: '648839958281',
    projectId: 'regmonu',
    storageBucket: 'regmonu.appspot.com',
    iosBundleId: 'com.example.monureg.RunnerTests',
  );
}
